def main_menu():
    print("수강신청")
    print("학사관리")
    print("1. 학생 정보 입력")
    print("2. 학생 정보 보기")
    print("3. 학생 정보 삭제")
    print("4. 학생 정보 수정")
    print("5. 정보 검색")
    print("6. 데이터 초기화")
    print("7. 자동 데이터 생성")
    print("8. 종료")
    print("===============")
    print("메뉴 선택")
    menu = int(input())
    return menu
